--
-- constants.lua
--
-- Proxy Binding Id
BRIGHTNESS_PROXY_BINDING = 5001
TEMPERATURE_PROXY_BINDING = 5002
RED_PROXY_BINDING = 5003
GREEN_PROXY_BINDING = 5004
BLUE_PROXY_BINDING = 5005

-- Control Binding Id
ON_BINDING = 300
OFF_BINDING = 301
TOGGLE_BINDING = 302

-- Property Name
RED_PROPERTY = "Red Value"
GREEN_PROPERTY = "Green Value"
BLUE_PROPERTY = "Blue Value"
BRIGHTNESS_PROPERTY = "Brightness"
COLOR_TEMPERATURE_PROPERTY = "Color Temperature"

-- Mode
RGB_MODE = "RGB"
TEMPERATURE_MODE = "Temperature Mode"
